name: Benchmark

on:
  push:
    branches:
      - main

jobs:
  benchmark:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.19.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v2

    - name: Benchmark
      run: go test -timeout=20m -benchmem -benchtime=2x -bench=. ./src/usecase

       